# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomb_id', models.CharField(max_length=10)),
                ('tomb_type', models.CharField(max_length=20)),
                ('tomb_count', models.BigIntegerField()),
                ('tomb_size', models.CharField(max_length=8)),
                ('tomb_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('receipt_date', models.DateTimeField(auto_now=True)),
                ('operator', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
