# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20171031_1652'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='material',
            table='materials',
        ),
    ]
