# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20171031_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
