# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0004_delete_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mater_code', models.CharField(max_length=10)),
                ('mater_name', models.CharField(max_length=40)),
                ('mater_model', models.CharField(max_length=8)),
                ('receipt_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('receipt_count', models.BigIntegerField()),
                ('receipt_date', models.DateTimeField(auto_now=True)),
                ('operator', models.CharField(max_length=12)),
            ],
        ),
    ]
