# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
