# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='material',
            table=None,
        ),
    ]
