# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 08:52
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('born_date', models.DateField()),
                ('address', models.TextField()),
                ('work_unit', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('contact', models.CharField(max_length=17)),
                ('introduce', models.TextField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'person',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
