# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteries', '0006_auto_20171117_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grave',
            name='grave_pic',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
