# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteries', '0009_auto_20171119_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.AddField(
            model_name='grave',
            name='picture_name',
            field=models.CharField(default='%Y%m%d.jpg', max_length=20),
        ),
    ]
