# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteries', '0010_auto_20171119_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=10)),
                ('area_name', models.CharField(max_length=20)),
                ('remark', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('operator', models.CharField(max_length=12)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('modify_user', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='TombArea',
        ),
    ]
