# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteries', '0011_auto_20171120_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_code', models.CharField(max_length=10)),
                ('cate_name', models.CharField(max_length=20)),
                ('cate_type', models.CharField(choices=[('单', '单墓'), ('双', '双墓')], default='单', max_length=4)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('modify_date', models.DateTimeField(auto_now_add=True)),
                ('modify_user', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
