# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteries', '0013_tomb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomb',
            name='area',
        ),
        migrations.RemoveField(
            model_name='tomb',
            name='cate',
        ),
        migrations.RemoveField(
            model_name='tomb',
            name='grave',
        ),
        migrations.AlterField(
            model_name='cate',
            name='cate_type',
            field=models.CharField(choices=[('单', '单墓'), ('双', '双墓'), ('多人墓', '多人墓')], default='单', max_length=4),
        ),
        migrations.DeleteModel(
            name='Tomb',
        ),
    ]
